Repository yashk2000/SneakySketchers, pull requests merged in 2020-11, with the labels that each got.

#7 notebook : inpainting workflow
  Inpainting.ipynb
Labels: Notebook

#10 frontend: Finalize Ui and code cleanup
  .gitattributes
  InPainting Notebook/Inpainting.ipynb
  application/gui/__init__.py
  application/gui/draw.py
  application/gui/icon.png
  application/gui/model.pth
  application/gui/model.py
  application/gui/window.py
  application/main.py
  application/model.pth
  application/pconv/__init__.py
  application/pconv/loss.py
  application/pconv/model.py
  application/util/__init__.py
  application/util/util.py
  gui/ui_model.py
  ui_main.py
Labels: PyQt-UI, enhancement

#12 general: Add issue templates to the repo
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#18 general: Add contributors guidelines
  CONTRIBUTING.md
Labels: documentation

#16 general: Add code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#14 general: Add pull request templates
  .github/PULL_REQUEST_TEMPLATE
Labels: documentation
